/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#141b2b",
        "surface-container-low": "#191b23",
        "surface": "#10131a",
        "outline": "#8c909f",
        "outline-variant": "#424754",
        "on-primary-container": "#00285d",
        "background": "#10131a",
        "on-primary-fixed": "#001a42",
        "tertiary-container": "#df7412",
        "on-background": "#e1e2ec",
        "surface-dim": "#10131a",
        "inverse-primary": "#005ac2",
        "secondary-fixed": "#dce2f7",
        "inverse-surface": "#e1e2ec",
        "on-surface": "#e1e2ec",
        "tertiary-fixed-dim": "#ffb786",
        "primary-fixed-dim": "#adc6ff",
        "secondary": "#c0c6db",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#502400",
        "on-secondary": "#293040",
        "tertiary-fixed": "#ffdcc6",
        "on-error": "#690005",
        "primary-container": "#4d8eff",
        "surface-tint": "#adc6ff",
        "surface-container-high": "#272a31",
        "on-primary": "#002e6a",
        "primary": "#adc6ff",
        "error": "#ffb4ab",
        "secondary-container": "#404758",
        "on-tertiary-container": "#461f00",
        "secondary-fixed-dim": "#c0c6db",
        "surface-container-highest": "#32353c",
        "on-surface-variant": "#c2c6d6",
        "on-secondary-fixed-variant": "#404758",
        "on-tertiary-fixed-variant": "#723600",
        "surface-variant": "#32353c",
        "on-secondary-container": "#aeb5c9",
        "inverse-on-surface": "#2e3038",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#004395",
        "surface-bright": "#363941",
        "tertiary": "#ffb786",
        "primary-fixed": "#d8e2ff",
        "surface-container-lowest": "#0b0e15",
        "on-tertiary-fixed": "#311400",
        "surface-container": "#1d2027"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xl": "40px",
        "gutter": "16px",
        "margin": "24px",
        "md": "16px",
        "sm": "8px",
        "unit": "4px",
        "xs": "4px",
        "lg": "24px"
      },
      fontFamily: {
        "h2": ["Inter"],
        "label": ["Inter"],
        "h1": ["Inter"],
        "body": ["Inter"],
        "data-lg": ["JetBrains Mono"],
        "data-sm": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "data-md": ["JetBrains Mono"]
      },
      fontSize: {
        "h2": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label": ["11px", { "lineHeight": "1", "letterSpacing": "0.08em", "fontWeight": "700" }],
        "h1": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body": ["16px", { "lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400" }],
        "data-lg": ["20px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "data-sm": ["12px", { "lineHeight": "1.4", "letterSpacing": "0.04em", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400" }],
        "data-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
